import base64
import urllib.parse
import requests

POLLINATIONS_BASE = "https://image.pollinations.ai/prompt/"


def _generate_panel_image(caption):
    """
    Generate a single comic-style image for a caption using Pollinations.ai
    (free, no API key, no Gemini quota used). Returns (data_uri_or_None, error_or_None).
    """
    prompt = f"colorful comic book panel illustration, no text, no speech bubbles: {caption}"

    try:
        encoded_prompt = urllib.parse.quote(prompt)
        url = f"{POLLINATIONS_BASE}{encoded_prompt}?width=768&height=512&nologo=true&model=flux"

        resp = requests.get(url, timeout=60)
        resp.raise_for_status()

        b64_data = base64.b64encode(resp.content).decode("utf-8")
        return f"data:image/jpeg;base64,{b64_data}", None

    except requests.RequestException as e:
        return None, str(e)


def build_panels_from_captions(panel_captions):
    """
    Takes a list of caption strings (already generated by Gemini elsewhere)
    and generates an image for each via Pollinations.
    Returns: [{"caption": str, "imageBase64": str}, ...]
    """
    panels = []
    for caption in panel_captions:
        image_data_uri, error = _generate_panel_image(caption)
        panels.append({
            "caption": caption,
            "imageBase64": image_data_uri or ""
        })

    if all(p["imageBase64"] == "" for p in panels):
        raise ValueError(
            "Image generation failed for all panels. The image service may be "
            "temporarily unavailable — please try again."
        )

    return panels
